# Program 11

Write a program using working on Deep Learning Data Structures.

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
#Creating tensors and arrays
tensor = tf.constant([[1,2,3],[4,5,6]])
array = np.array([[7,8,9],[10,11,12]])

In [4]:
#Performing operations
addition = tensor + array
multiplication = tensor * array
matrix_product = tf.matmul(tensor,array.T)

In [5]:
#Converting between tensors and arrays
tensor_to_array = tensor.numpy()
array_to_tensor = tf.convert_to_tensor(array)

In [6]:
#Printing the results
print('Original Tensor:')
print(tensor)
print('\nOriginal Array:')
print(array)
print('\nElement wise addition:')
print(addition)
print('\nElement wise multiplication:')
print(multiplication)
print('\nMatrix Product:')
print(matrix_product)
print('\nTensor Converted to Array:')
print(tensor_to_array)
print('\nArray Converted to Tensor:')
print(array_to_tensor)

Original Tensor:
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)

Original Array:
[[ 7  8  9]
 [10 11 12]]

Element wise addition:
tf.Tensor(
[[ 8 10 12]
 [14 16 18]], shape=(2, 3), dtype=int32)

Element wise multiplication:
tf.Tensor(
[[ 7 16 27]
 [40 55 72]], shape=(2, 3), dtype=int32)

Matrix Product:
tf.Tensor(
[[ 50  68]
 [122 167]], shape=(2, 2), dtype=int32)

Tensor Converted to Array:
[[1 2 3]
 [4 5 6]]

Array Converted to Tensor:
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)
